
export type Quote = {
  quote: string;
  source: string;
};

export const quotes: Quote[] = [
  { quote: "The sun will shine on us again.", source: "Loki (Marvel)" },
  { quote: "Everything is awesome!", source: "Emmet (The LEGO Movie)" },
  { quote: "It’s not who I am underneath, but what I do that defines me.", source: "Batman" },
  { quote: "Just keep swimming.", source: "Dory (Finding Nemo)" },
  { quote: "The way I see it, if you want the rainbow, you gotta put up with the rain.", source: "Dolly Parton" },
  { quote: "Happiness can be found even in the darkest of times, if one only remembers to turn on the light.", source: "Albus Dumbledore" },
  { quote: "Do or do not. There is no try.", source: "Yoda" },
  { quote: "I can do this all day.", source: "Captain America" },
  { quote: "Your focus determines your reality.", source: "Qui-Gon Jinn" },
  { quote: "To infinity and beyond!", source: "Buzz Lightyear" },
  { quote: "The only way to achieve the impossible is to believe it is possible.", source: "Charles Kingsleigh (Alice in Wonderland)" },
  { quote: "The problem is not the problem. The problem is your attitude about the problem.", source: "Jack Sparrow" },
  { quote: "Great men are not born great, they grow great.", source: "Vito Corleone" },
  { quote: "Whatever you are, be a good one.", source: "Abraham Lincoln" },
  { quote: "The best way to predict the future is to create it.", source: "Peter Drucker" },
  { quote: "Every strike brings me closer to the next home run.", source: "Babe Ruth" },
  { quote: "Believe you can and you're halfway there.", source: "Theodore Roosevelt" },
  { quote: "Act as if what you do makes a difference. It does.", source: "William James" },
  { quote: "No matter what people tell you, words and ideas can change the world.", source: "Robin Williams" },
  { quote: "Oh yes, the past can hurt. But the way I see it, you can either run from it or learn from it.", source: "Rafiki" },
  { quote: "Success is not final, failure is not fatal: it is the courage to continue that counts.", source: "Winston Churchill" },
  { quote: "Our lives are defined by opportunities, even the ones we miss.", source: "Benjamin Button" },
  { quote: "Don't let anyone ever make you feel like you don't deserve what you want.", source: "Patrick Verona (10 Things I Hate About You)" },
  { quote: "Why do we fall, sir? So that we can learn to pick ourselves up.", source: "Alfred Pennyworth" },
  { quote: "Life moves pretty fast. If you don't stop and look around once in a while, you could miss it.", source: "Ferris Bueller" },
  { quote: "Even the smallest person can change the course of the future.", source: "Galadriel" },
  { quote: "You must be the change you wish to see in the world.", source: "Mahatma Gandhi" },
  { quote: "Spread love everywhere you go. Let no one ever come to you without leaving happier.", source: "Mother Teresa" },
  { quote: "The only true wisdom is in knowing you know nothing.", source: "Socrates" },
  { quote: "The journey of a thousand miles begins with one step.", source: "Lao Tzu" },
  { quote: "Dream as if you'll live forever. Live as if you'll die today.", source: "James Dean" },
  { quote: "Stay hungry, stay foolish.", source: "Steve Jobs" },
  { quote: "In the middle of every difficulty lies opportunity.", source: "Albert Einstein" },
  { quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", source: "Ralph Waldo Emerson" },
  { quote: "Sometimes the right path is not the easiest one.", source: "Grandmother Willow (Pocahontas)" },
  { quote: "It is our choices that show what we truly are, far more than our abilities.", source: "Albus Dumbledore" },
  { quote: "Courage is being scared to death, but saddling up anyway.", source: "John Wayne" },
  { quote: "The only limit to our realization of tomorrow will be our doubts of today.", source: "Franklin D. Roosevelt" },
  { quote: "Do what you can, with what you have, where you are.", source: "Theodore Roosevelt" },
  { quote: "The future belongs to those who believe in the beauty of their dreams.", source: "Eleanor Roosevelt" },
  { quote: "Don't count the days, make the days count.", source: "Muhammad Ali" },
  { quote: "A hero can be anyone.", source: "Batman" },
  { quote: "I’m a big fan of ignoreland. When you can’t change it, ignore it.", source: "Ted Lasso" },
  { quote: "If you’re going through hell, keep going.", source: "Winston Churchill" },
  { quote: "You miss 100% of the shots you don't take.", source: "Wayne Gretzky" },
  { quote: "The mind is everything. What you think you become.", source: "Buddha" },
  { quote: "Everything you’ve ever wanted is on the other side of fear.", source: "George Addair" },
  { quote: "Keep your face always toward the sunshine, and shadows will fall behind you.", source: "Walt Whitman" },
  { quote: "Positive anything is better than negative nothing.", source: "Elbert Hubbard" },
  { quote: "The power of imagination makes us infinite.", source: "John Muir" },
  { quote: "I am Groot.", source: "Groot" },
  { quote: "There’s no place like home.", source: "Dorothy (The Wizard of Oz)" },
  { quote: "May the Force be with you.", source: "Star Wars" },
  { quote: "I'm the king of the world!", source: "Jack Dawson (Titanic)" },
  { quote: "Carpe diem. Seize the day, boys. Make your lives extraordinary.", source: "John Keating (Dead Poets Society)" },
  { quote: "What we do in life echoes in eternity.", source: "Maximus (Gladiator)" },
  { quote: "It’s a-me, Mario!", source: "Mario" },
  { quote: "The greatest glory in living lies not in never falling, but in rising every time we fall.", source: "Nelson Mandela" },
  { quote: "The way to get started is to quit talking and begin doing.", source: "Walt Disney" },
  { quote: "Your time is limited, so don't waste it living someone else's life.", source: "Steve Jobs" },
  { quote: "If life were predictable it would cease to be life, and be without flavor.", source: "Eleanor Roosevelt" },
  { quote: "If you look at what you have in life, you'll always have more.", source: "Oprah Winfrey" },
  { quote: "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.", source: "James Cameron" },
  { quote: "Life is what happens when you're busy making other plans.", source: "John Lennon" },
  { quote: "You will face many defeats in life, but never let yourself be defeated.", source: "Maya Angelou" },
  { quote: "The purpose of our lives is to be happy.", source: "Dalai Lama" },
  { quote: "Life is a succession of lessons which must be lived to be understood.", source: "Ralph Waldo Emerson" },
  { quote: "You only live once, but if you do it right, once is enough.", source: "Mae West" },
  { quote: "Live in the sunshine, swim the sea, drink the wild air.", source: "Ralph Waldo Emerson" },
  { quote: "Go confidently in the direction of your dreams! Live the life you've imagined.", source: "Henry David Thoreau" },
  { quote: "The two most important days in your life are the day you are born and the day you find out why.", source: "Mark Twain" },
  { quote: "It is never too late to be what you might have been.", source: "George Eliot" },
  { quote: "Everything has beauty, but not everyone can see.", source: "Confucius" },
  { quote: "The most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.", source: "Helen Keller" },
  { quote: "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.", source: "Jordan Belfort" },
  { quote: "Strive not to be a success, but rather to be of value.", source: "Albert Einstein" },
  { quote: "I have not failed. I've just found 10,000 ways that won't work.", source: "Thomas A. Edison" },
  { quote: "A creative man is motivated by the desire to achieve, not by the desire to beat others.", source: "Ayn Rand" },
  { quote: "If you want to live a happy life, tie it to a goal, not to people or things.", source: "Albert Einstein" },
  { quote: "The only source of knowledge is experience.", source: "Albert Einstein" },
  { quote: "What is important is to keep learning, to enjoy challenge, and to tolerate ambiguity. In the end there are no certain answers.", source: "Matina Horner" },
  { quote: "A person who never made a mistake never tried anything new.", source: "Albert Einstein" },
  { quote: "Try not to become a man of success. Rather become a man of value.", source: "Albert Einstein" },
  { quote: "The true sign of intelligence is not knowledge but imagination.", source: "Albert Einstein" },
  { quote: "We cannot solve our problems with the same thinking we used when we created them.", source: "Albert Einstein" },
  { quote: "Learn from yesterday, live for today, hope for tomorrow. The important thing is not to stop questioning.", source: "Albert Einstein" },
  { quote: "Anyone who has never made a mistake has never tried anything new.", source: "Albert Einstein" },
  { quote: "I have no special talent. I am only passionately curious.", source: "Albert Einstein" },
  { quote: "Look deep into nature, and then you will understand everything better.", source: "Albert Einstein" },
  { quote: "Life is like riding a bicycle. To keep your balance, you must keep moving.", source: "Albert Einstein" },
  { quote: "No amount of experimentation can ever prove me right; a single experiment can prove me wrong.", source: "Albert Einstein" },
  { quote: "Only a life lived for others is a life worthwhile.", source: "Albert Einstein" },
  { quote: "The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.", source: "Albert Einstein" },
  { quote: "There are two ways to live: you can live as if nothing is a miracle; you can live as if everything is a miracle.", source: "Albert Einstein" },
  { quote: "Peace cannot be kept by force; it can only be achieved by understanding.", source: "Albert Einstein" },
  { quote: "Imagination is everything. It is the preview of life's coming attractions.", source: "Albert Einstein" },
  { quote: "The important thing is not to stop questioning. Curiosity has its own reason for existing.", source: "Albert Einstein" },
  { quote: "Science without religion is lame, religion without science is blind.", source: "Albert Einstein" },
  { quote: "Gravity is not responsible for people falling in love.", source: "Albert Einstein" },
  { quote: "The measure of intelligence is the ability to change.", source: "Albert Einstein" },
  { quote: "Reality is merely an illusion, albeit a very persistent one.", source: "Albert Einstein" },
  { quote: "It is the supreme art of the teacher to awaken joy in creative expression and knowledge.", source: "Albert Einstein" },
  { quote: "Once we accept our limits, we go beyond them.", source: "Albert Einstein" },
  { quote: "Genius is 1% talent and 99% percent hard work.", source: "Albert Einstein" },
  { quote: "Black holes are where God divided by zero.", source: "Albert Einstein" },
  { quote: "If you can't explain it simply, you don't understand it well enough.", source: "Albert Einstein" },
  { quote: "The most incomprehensible thing about the world is that it is comprehensible.", source: "Albert Einstein" },
  { quote: "I know not with what weapons World War III will be fought, but World War IV will be fought with sticks and stones.", source: "Albert Einstein" },
  { quote: "You never fail until you stop trying.", source: "Albert Einstein" },
  { quote: "Weakness of attitude becomes weakness of character.", source: "Albert Einstein" },
  { quote: "A clever person solves a problem. A wise person avoids it.", source: "Albert Einstein" },
  { quote: "Logic will get you from A to B. Imagination will take you everywhere.", source: "Albert Einstein" },
  { quote: "The world is a dangerous place to live, not because of the people who are evil, but because of the people who don't do anything about it.", source: "Albert Einstein" },
  { quote: "When you are courting a nice girl an hour seems like a second. When you sit on a red-hot cinder a second seems like an hour. That's relativity.", source: "Albert Einstein" },
  { quote: "If A is a success in life, then A equals x plus y plus z. Work is x; y is play; and z is keeping your mouth shut.", source: "Albert Einstein" },
  { quote: "All that is gold does not glitter, not all those who wander are lost.", source: "J.R.R. Tolkien" },
  { quote: "The secret of getting ahead is getting started.", source: "Mark Twain" },
  { quote: "It's not the years in your life that count. It's the life in your years.", source: "Abraham Lincoln" },
  { quote: "Many of life's failures are people who did not realize how close they were to success when they gave up.", source: "Thomas A. Edison" },
  { quote: "The future is not something we enter. The future is something we create.", source: "Leonard I. Sweet" },
  { quote: "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.", source: "Winston Churchill" },
  { quote: "Don't judge each day by the harvest you reap but by the seeds that you plant.", source: "Robert Louis Stevenson" },
  { quote: "The only impossible journey is the one you never begin.", source: "Tony Robbins" },
  { quote: "In this life we cannot do great things. We can only do small things with great love.", source: "Mother Teresa" },
  { quote: "You are never too old to set another goal or to dream a new dream.", source: "C.S. Lewis" },
  { quote: "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.", source: "Ralph Waldo Emerson" },
  { quote: "What we think, we become.", source: "Buddha" },
  { quote: "May your choices reflect your hopes, not your fears.", source: "Nelson Mandela" },
  { quote: "There is no greater agony than bearing an untold story inside you.", source: "Maya Angelou" },
  { quote: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", source: "Aristotle" },
  { quote: "The greatest wealth is to live content with little.", source: "Plato" },
  { quote: "The secret of happiness, you see, is not found in seeking more, but in developing the capacity to enjoy less.", source: "Socrates" },
  { quote: "It is not death that a man should fear, but he should fear never beginning to live.", source: "Marcus Aurelius" },
  { quote: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", source: "Ralph Waldo Emerson" },
  { quote: "There is no charm equal to tenderness of heart.", source: "Jane Austen" },
  { quote: "The only person you are destined to become is the person you decide to be.", source: "Ralph Waldo Emerson" },
  { quote: "Go forth and set the world on fire.", source: "Ignatius of Loyola" },
  { quote: "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.", source: "Plato" },
  { quote: "When you arise in the morning, think of what a precious privilege it is to be alive - to breathe, to think, to enjoy, to love.", source: "Marcus Aurelius" },
  { quote: "The happiness of your life depends upon the quality of your thoughts.", source: "Marcus Aurelius" },
  { quote: "Waste no more time arguing about what a good man should be. Be one.", source: "Marcus Aurelius" },
  { quote: "It’s not what happens to you, but how you react to it that matters.", source: "Epictetus" },
  { quote: "The best revenge is to be unlike him who performed the injury.", source: "Marcus Aurelius" },
  { quote: "The soul becomes dyed with the colour of its thoughts.", source: "Marcus Aurelius" },
  { quote: "He who lives in harmony with himself lives in harmony with the universe.", source: "Marcus Aurelius" },
  { quote: "You have power over your mind - not outside events. Realize this, and you will find strength.", source: "Marcus Aurelius" },
  { quote: "Accept the things to which fate binds you, and love the people with whom fate brings you together, but do so with all your heart.", source: "Marcus Aurelius" },
  { quote: "The object of life is not to be on the side of the majority, but to escape finding oneself in the ranks of the insane.", source: "Marcus Aurelius" },
  { quote: "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", source: "Marcus Aurelius" },
  { quote: "The first rule of Fight Club is: You do not talk about Fight Club.", source: "Fight Club" },
  { quote: "I'm going to make him an offer he can't refuse.", source: "The Godfather" },
  { quote: "Houston, we have a problem.", source: "Apollo 13" },
  { quote: "You're gonna need a bigger boat.", source: "Jaws" },
  { quote: "I'll be back.", source: "The Terminator" },
  { quote: "Go ahead, make my day.", source: "Sudden Impact" },
  { quote: "Nobody puts Baby in a corner.", source: "Dirty Dancing" },
  { quote: "I am serious. And don't call me Shirley.", source: "Airplane!" },
  { quote: "Here's looking at you, kid.", source: "Casablanca" },
  { quote: "I feel the need—the need for speed!", source: "Top Gun" },
  { quote: "The stuff that dreams are made of.", source: "The Maltese Falcon" },
  { quote: "E.T. phone home.", source: "E.T. the Extra-Terrestrial" },
  { quote: "You can't handle the truth!", source: "A Few Good Men" },
  { quote: "A martini. Shaken, not stirred.", source: "James Bond" },
  { quote: "This is the beginning of a beautiful friendship.", source: "Casablanca" },
  { quote: "I see dead people.", source: "The Sixth Sense" },
  { quote: "Bond. James Bond.", source: "James Bond" },
  { quote: "Elementary, my dear Watson.", source: "Sherlock Holmes" },
  { quote: "That'll do, pig. That'll do.", source: "Babe" },
  { quote: "Chewie, we’re home.", source: "Star Wars: The Force Awakens" },
  { quote: "I'm having an old friend for dinner.", source: "The Silence of the Lambs" },
  { quote: "Roads? Where we're going we don't need roads.", source: "Back to the Future" },
  { quote: "Say 'hello' to my little friend!", source: "Scarface" },
  { quote: "What's in the box?", source: "Se7en" },
  { quote: "I am your father.", source: "Star Wars: The Empire Strikes Back" },
  { quote: "Why so serious?", source: "The Dark Knight" },
  { quote: "Some people can’t believe in themselves until someone else believes in them first.", source: "Good Will Hunting" },
  { quote: "It is not our abilities that show what we truly are… it is our choices.", source: "Harry Potter and the Chamber of Secrets" },
  { quote: "All we have to decide is what to do with the time that is given us.", source: "The Lord of the Rings: The Fellowship of the Ring" },
  { quote: "Your time as a caterpillar has expired. Your wings are ready.", source: "Unknown" },
  { quote: "The very things that hold you down are going to lift you up.", source: "Dumbo" },
  { quote: "The past is just a story we tell ourselves.", source: "Her" },
  { quote: "You are the hero of your own story.", source: "Unknown" },
  { quote: "A little consideration, a little thought for others, makes all the difference.", source: "Winnie the Pooh" },
  { quote: "The moment you doubt whether you can fly, you cease for ever to be able to do it.", source: "Peter Pan" },
  { quote: "You're mad. Bonkers. Off your head. But I'll tell you a secret: all the best people are.", source: "Alice in Wonderland" },
  { quote: "The world is not in your books and maps, it’s out there.", source: "The Hobbit" },
  { quote: "Adventure is out there!", source: "Up" },
  { quote: "There is a great deal of difference between an eager man who wants to read a book and a tired man who wants a book to read.", source: "G.K. Chesterton" },
  { quote: "Today is a good day to try.", source: "The Hunchback of Notre Dame" },
  { quote: "I shall not waste my days in trying to prolong them. I shall use my time.", source: "The Lord of the Rings" },
  { quote: "You are not a drop in the ocean. You are the entire ocean in a drop.", source: "Rumi" },
  { quote: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", source: "Rumi" },
  { quote: "Raise your words, not your voice. It is rain that grows flowers, not thunder.", source: "Rumi" },
  { quote: "The wound is the place where the Light enters you.", source: "Rumi" },
  { quote: "What you seek is seeking you.", source: "Rumi" },
  { quote: "Don't grieve. Anything you lose comes round in another form.", source: "Rumi" },
  { quote: "Stop acting so small. You are the universe in ecstatic motion.", source: "Rumi" },
  { quote: "The quieter you become, the more you are able to hear.", source: "Rumi" },
  { quote: "Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it.", source: "Rumi" },
  { quote: "The only lasting beauty is the beauty of the heart.", source: "Rumi" },
  { quote: "Let yourself be silently drawn by the strange pull of what you really love. It will not lead you astray.", source: "Rumi" },
  { quote: "Yesterday is history, tomorrow is a mystery, but today is a gift. That is why it is called the present.", source: "Master Oogway (Kung Fu Panda)" },
  { quote: "When you do things from your soul, you feel a river moving in you, a joy.", source: "Rumi" },
  { quote: "The world is full of magical things patiently waiting for our wits to grow sharper.", source: "Bertrand Russell" },
  { quote: "Our job is to love others without stopping to inquire whether or not they are worthy.", source: "Thomas Merton" },
  { quote: "The desire to know your own soul will end all other desires.", source: "Rumi" },
  { quote: "Where there is ruin, there is hope for a treasure.", source: "Rumi" },
  { quote: "Be like a tree and let the dead leaves drop.", source: "Rumi" },
  { quote: "The art of knowing is knowing what to ignore.", source: "Rumi" },
  { quote: "If you are irritated by every rub, how will your mirror be polished?", source: "Rumi" },
  { quote: "Two there are who are never satisfied -- the lover of the world and the lover of knowledge.", source: "Rumi" },
  { quote: "Don't be satisfied with stories, how things have gone with others. Unfold your own myth.", source: "Rumi" },
  { quote: "Sell your cleverness and buy bewilderment.", source: "Rumi" },
  { quote: "Respond to every call that excites your spirit.", source: "Rumi" },
  { quote: "Let the beauty we love be what we do.", source: "Rumi" },
  { quote: "Set your life on fire. Seek those who fan your flames.", source: "Rumi" },
  { quote: "Your heart knows the way. Run in that direction.", source: "Rumi" },
  { quote: "Be empty of worrying. Think of who created thought.", source: "Rumi" },
  { quote: "The moon stays bright when it doesn't avoid the night.", source: "Rumi" },
  { quote: "It's your road, and yours alone. Others may walk it with you, but no one can walk it for you.", source: "Rumi" },
  { quote: "I am not this hair, I am not this skin, I am the soul that lives within.", source: "Rumi" },
  { quote: "To be happy is a choice. You can choose to be happy. There's going to be stress in life, but it's your choice whether you let it affect you or not.", source: "Valerie Bertinelli" },
  { quote: "The greatest discovery of all time is that a person can change his future by merely changing his attitude.", source: "Oprah Winfrey" },
  { quote: "Optimism is the one quality more associated with success and happiness than any other.", source: "Brian Tracy" },
  { quote: "Your positive action combined with positive thinking results in success.", source: "Shiv Khera" },
  { quote: "The more you are in a state of gratitude, the more you will attract things to be grateful for.", source: "Rhonda Byrne" },
  { quote: "What you have done is nothing compared to what you can do.", source: "Unknown" },
  { quote: "The most important thing is to enjoy your life - to be happy - it's all that matters.", source: "Audrey Hepburn" },
  { quote: "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears.", source: "Chantal Sutherland" },
  { quote: "I am thankful for all of those who said NO to me. It’s because of them I’m doing it myself.", source: "Albert Einstein" },
  { quote: "Today’s special moments are tomorrow’s memories.", source: "Genie (Aladdin)" },
  { quote: "Build your own dreams, or someone else will hire you to build theirs.", source: "Farrah Gray" },
  { quote: "The only way to do great work is to love what you do.", source: "Steve Jobs" },
  { quote: "The best time to plant a tree was 20 years ago. The second best time is now.", source: "Chinese Proverb" },
  { quote: "You can, you should, and if you’re brave enough to start, you will.", source: "Stephen King" },
  { quote: "The successful warrior is the average man, with laser-like focus.", source: "Bruce Lee" },
  { quote: "Don't be afraid to give up the good to go for the great.", source: "John D. Rockefeller" },
  { quote: "If you are not willing to risk the usual, you will have to settle for the ordinary.", source: "Jim Rohn" },
  { quote: "All our dreams can come true, if we have the courage to pursue them.", source: "Walt Disney" },
  { quote: "If you do what you’ve always done, you’ll get what you’ve always gotten.", source: "Tony Robbins" },
  { quote: "Success is walking from failure to failure with no loss of enthusiasm.", source: "Winston Churchill" },
  { quote: "Opportunities don't happen. You create them.", source: "Chris Grosser" },
  { quote: "I find that the harder I work, the more luck I seem to have.", source: "Thomas Jefferson" },
  { quote: "The road to success and the road to failure are almost exactly the same.", source: "Colin R. Davis" },
  { quote: "Success usually comes to those who are too busy to be looking for it.", source: "Henry David Thoreau" },
  { quote: "Don't be distracted by criticism. Remember -- the only taste of success some people get is to take a bite out of you.", source: "Zig Ziglar" },
  { quote: "I never dreamed about success. I worked for it.", source: "Estée Lauder" },
  { quote: "There is no substitute for hard work.", source: "Thomas Edison" },
  { quote: "What seems to us as bitter trials are often blessings in disguise.", source: "Oscar Wilde" },
  { quote: "The distance between insanity and genius is measured only by success.", source: "Bruce Feirstein" },
  { quote: "I cannot give you the formula for success, but I can give you the formula for failure--It is: Try to please everybody.", source: "Herbert Bayard Swope" },
  { quote: "The real test is not whether you avoid this failure, because you won't. It's whether you let it harden or shame you into inaction, or whether you learn from it; whether you choose to persevere.", source: "Barack Obama" },
  { quote: "The price of success is hard work, dedication to the job at hand, and the determination that whether we win or lose, we have applied the best of ourselves to the task at hand.", source: "Vince Lombardi" },
  { quote: "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.", source: "Colin Powell" },
  { quote: "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", source: "Albert Schweitzer" },
  { quote: "To succeed in life, you need two things: ignorance and confidence.", source: "Mark Twain" },
  { quote: "I'm a success today because I had a friend who believed in me and I didn't have the heart to let him down.", source: "Abraham Lincoln" },
  { quote: "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.", source: "David Brinkley" },
  { quote: "Things work out best for those who make the best of how things work out.", source: "John Wooden" },
  { quote: "Try not to become a person of success, but rather try to become a person of value.", source: "Albert Einstein" },
  { quote: "Never give in except to convictions of honor and good sense.", source: "Winston Churchill" },
  { quote: "Stop chasing the money and start chasing the passion.", source: "Tony Hsieh" },
  { quote: "Success is liking yourself, liking what you do, and liking how you do it.", source: "Maya Angelou" },
  { quote: "If you want to make a permanent change, stop focusing on the size of your problems and start focusing on the size of you!", source: "T. Harv Eker" },
  { quote: "The number one reason people fail in life is because they listen to their friends, family, and neighbors.", source: "Napoleon Hill" },
  { quote: "You know you are on the road to success if you would do your job, and not be paid for it.", source: "Oprah Winfrey" },
  { quote: "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.", source: "Vince Lombardi" },
  { quote: "Fall seven times and stand up eight.", source: "Japanese Proverb" },
  { quote: "Some people dream of success while others wake up and work hard at it.", source: "Napoleon Hill" },
  { quote: "If you don’t design your own life plan, chances are you’ll fall into someone else’s plan. And guess what they have planned for you? Not much.", source: "Jim Rohn" },
  { quote: "If you aren't going all the way, why go at all?", source: "Joe Namath" },
  { quote: "The question isn’t who is going to let me; it’s who is going to stop me.", source: "Ayn Rand" },
  { quote: "The only place where success comes before work is in the dictionary.", source: "Vidal Sassoon" },
  { quote: "Keep on going, and the chances are that you will stumble on something, perhaps when you are least expecting it. I never heard of anyone ever stumbling on something sitting down.", source: "Charles F. Kettering" },
  { quote: "I will not let anyone walk through my mind with their dirty feet.", source: "Mahatma Gandhi" },
  { quote: "We are still masters of our fate. We are still captains of our souls.", source: "Winston Churchill" },
  { quote: "Our greatest fear should not be of failure but of succeeding at things in life that don't really matter.", source: "Francis Chan" },
  { quote: "Be yourself; everyone else is already taken.", source: "Oscar Wilde" },
  { quote: "I'm so clever that sometimes I don't understand a single word of what I am saying.", source: "Oscar Wilde" },
  { quote: "To live is the rarest thing in the world. Most people exist, that is all.", source: "Oscar Wilde" },
  { quote: "True friends stab you in the front.", source: "Oscar Wilde" },
  { quote: "Always forgive your enemies; nothing annoys them so much.", source: "Oscar Wilde" },
  { quote: "The truth is rarely pure and never simple.", source: "Oscar Wilde" },
  { quote: "A good friend will always stab you in the front.", source: "Oscar Wilde" },
  { quote: "I have the simplest of tastes. I am always satisfied with the best.", source: "Oscar Wilde" },
  { quote: "To love oneself is the beginning of a lifelong romance.", source: "Oscar Wilde" },
  { quote: "Be yourself, but be your best self.", source: "Oscar Wilde" },
  { quote: "You can never be overdressed or overeducated.", source: "Oscar Wilde" },
  { quote: "A man who does not think for himself does not think at all.", source: "Oscar Wilde" },
  { quote: "Life is not a problem to be solved, but a reality to be experienced.", source: "Søren Kierkegaard" },
  { quote: "The purpose of life is to be defeated by greater and greater things.", source: "Rainer Maria Rilke" },
  { quote: "There is nothing permanent except change.", source: "Heraclitus" },
  { quote: "Time is a created thing. To say 'I don't have time,' is like saying, 'I don't want to.'", source: "Lao Tzu" },
  { quote: "Change your thoughts and you change your world.", source: "Norman Vincent Peale" },
  { quote: "It is not in the stars to hold our destiny but in ourselves.", source: "William Shakespeare" },
  { quote: "A journey of a thousand miles must begin with a single step.", source: "Lao Tzu" },
  { quote: "I have not failed. I have just found 10,000 ways that won’t work.", source: "Thomas Edison" },
  { quote: "It does not matter how slowly you go as long as you do not stop.", source: "Confucius" },
  { quote: "I hear and I forget. I see and I remember. I do and I understand.", source: "Confucius" },
  { quote: "Choose a job you love, and you will never have to work a day in your life.", source: "Confucius" },
  { quote: "The will to win, the desire to succeed, the urge to reach your full potential... these are the keys that will unlock the door to personal excellence.", source: "Confucius" },
  { quote: "Our greatest glory is not in never falling, but in rising every time we fall.", source: "Confucius" },
  { quote: "The more man meditates upon good thoughts, the better will be his world and the world at large.", source: "Confucius" },
  { quote: "Wheresoever you go, go with all your heart.", source: "Confucius" },
  { quote: "I want to know God's thoughts... the rest are details.", source: "Albert Einstein" },
  { quote: "Everything that is really great and inspiring is created by the individual who can labor in freedom.", source: "Albert Einstein" },
  { quote: "Don't worry about your difficulties in Mathematics. I can assure you mine are still greater.", source: "Albert Einstein" },
  { quote: "Imagination is more important than knowledge.", source: "Albert Einstein" },
  { quote: "We still do not know one thousandth of one percent of what nature has revealed to us.", source: "Albert Einstein" },
  { quote: "One of the strongest characteristics of genius is the power of lighting its own fire.", source: "John Foster" },
  { quote: "The beginning is the most important part of the work.", source: "Plato" },
  { quote: "An ounce of prevention is worth a pound of cure.", source: "Benjamin Franklin" },
  { quote: "All you need is love. But a little chocolate now and then doesn't hurt.", source: "Charles M. Schulz" },
  { quote: "For every minute you are angry you lose sixty seconds of happiness.", source: "Ralph Waldo Emerson" },
  { quote: "It's no use going back to yesterday, because I was a different person then.", source: "Lewis Carroll" },
  { quote: "If you don't know where you are going, any road will get you there.", source: "Lewis Carroll" },
  { quote: "Would you tell me, please, which way I ought to go from here? 'That depends a good deal on where you want to get to,' said the Cat.", source: "Lewis Carroll" },
  { quote: "With great power comes great responsibility.", source: "Spider-Man" },
  { quote: "The flower that blooms in adversity is the most rare and beautiful of all.", source: "Mulan" },
  { quote: "It's just a flesh wound.", source: "Monty Python and the Holy Grail" },
];
